### ISSUE TITLE
Exclude beam-sdks-java-extensions-sql

### ISSUE THREAD

**Issue by istreeter** [snowplow-incubator/snowplow-google-cloud-storage-loader#80]
It brings in lots of unnecessary dependencies.  We don't use the sql feature of beam in Snowplow GCS loader.

**Comment by spenes** [comment]
Solved in this commit: https://github.com/snowplow-incubator/snowplow-google-cloud-storage-loader/commit/fce8cc4384624a4e5c247718f9b39163b87ae52b
